// example/src/pages/index/index.tsx
import React, { Component } from 'react'
import { View } from '@tarojs/components'
import './index.css'
import { routerService } from '../../service/routerService'

export default class Index extends Component {

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
        <View onClick={() => routerService.toTest({ id: 1 })}>点击跳转</View>
      </View>
    )
  }
}

// example/ts-vue/src/pages/index/index.vue
<template>
  <view class="index" @click="goSubPage">
    <text>{{ msg }}</text>
  </view>
</template>

<script>
import { ref } from 'vue'
import { routerService } from '../../service/routerService'
import './index.css'

export default {
  setup() {
    const msg = ref('主包页面-点击跳转到分包页面')
    return {
      msg,
    }
  },

  methods: {
    goSubPage() {
      routerService.toTest({ id: 1 })
    },
  },
}
</script>
